"""Criar tabelas iniciais: irrigation_data, sensor_readings, pest_detections

Revision ID: f8d6152866df
Revises: 
Create Date: 2025-11-22 13:30:37.049694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d6152866df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False, comment='Umidade do solo (%)'),
    sa.Column('ph', sa.Float(), nullable=False, comment='pH do solo'),
    sa.Column('phosphorus', sa.Float(), nullable=False, comment='Nível de fósforo (ppm)'),
    sa.Column('potassium', sa.Float(), nullable=False, comment='Nível de potássio (ppm)'),
    sa.Column('needs_irrigation', sa.Boolean(), nullable=False, comment='Necessita irrigação? (0=Não, 1=Sim)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pest_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pest_type', sa.String(length=100), nullable=False, comment='Tipo de praga detectada'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confiança da detecção (0-1)'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Localização da detecção'),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='Caminho da imagem'),
    sa.Column('alert_sent', sa.Boolean(), nullable=True, comment='Alerta AWS enviado?'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False, comment='ID do sensor ESP32'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Temperatura (°C)'),
    sa.Column('humidity', sa.Float(), nullable=True, comment='Umidade relativa do ar (%)'),
    sa.Column('soil_moisture', sa.Float(), nullable=True, comment='Umidade do solo (%)'),
    sa.Column('light_level', sa.Integer(), nullable=True, comment='Nível de luz (lux)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('pest_detections')
    op.drop_table('irrigation_data')
    # ### end Alembic commands ###
